Add option to provide ld-file for ld filtering the SNPs
dokyoonkimlab/netmage pull request #11
Opened 2020-11-13 15:24 UTC by manu148

2020-11-13 16:03 UTC, vsriram24 requested changes

2020-11-13 16:03 UTC, vsriram24 commented on scripts/prepDataForGephi.py
> +parser.add_argument('--input-files', dest= 'inputfiles', default = None, required = True, help='regular expression for input data file(s)')
How come you removed the metavar option from all arguments? I'd had it there so that if users typed something wrong, they would see how the argument should be formatted even if they didn't try to call help

2020-11-13 16:03 UTC, vsriram24 commented on scripts/prepDataForGephi.py
> +						edgeMapOutput.write(key1 + "\t" + key2 + "\t" + str(getLdPrunedCount(snpLdsetMap, sharedSNPs)) + "\t" + str(sharedSNPs) + "\n")
Looks good to me

2020-11-13 23:47 UTC, manu148 commented on scripts/prepDataForGephi.py
> +parser.add_argument('--input-files', dest= 'inputfiles', default = None, required = True, help='regular expression for input data file(s)')
modified the metavar and help. just keeping metavar looked ugly.

2020-11-14 15:10 UTC, vsriram24 approved these changes

2020-11-14 22:10 UTC, merged